### ISSUE TITLE
Difficulty installing

### ISSUE THREAD

**Issue by Cngg805** [hacktoolspack/hack-tools#28]
Hi! I'm new to coding with Python and stuff, and I'm having difficulties installing the hack tools. When I type "py file.py" into the python shell, it shows me a syntax error. Should I be replacing "file" with a file name from the hack-tools folder, and if so, what file?

**Comment by reuniware** [comment]
You should better type "python file.py" I think.

**Comment by hacktoolspack** [comment]
> 
> 
> Hi! I'm new to coding with Python and stuff, and I'm having difficulties installing the hack tools. When I type "py file.py" into the python shell, it shows me a syntax error. Should I be replacing "file" with a file name from the hack-tools folder, and if so, what file?

if it gives you a syntax error already checks that all the modules have been installed to launch the .py script.
