### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by aryan5555github** [hacktoolspack/hack-tools#42]
Tis code contains .exe files r they viruses? @hacktoolspack

**Comment by sabbajohn** [comment]
@aryan5555github please me, use a sandbox. Don't run directly on you machine. 
You can also check the file signature at virus total, most of RAT will accuse as Trojan or something like it. 
Anyway, use a Sandbox!

Happy hacking!

**Comment by aryan5555github** [comment]
Ok thanks @sabbajohn
